### ISSUE TITLE
Fatal error on custom taxonomy archive page

### ISSUE THREAD

**Issue by johnpuddephatt** [oomphinc/wp-dfp#5]
I have a custom taxonomy set up on my site. When I visit an archive page for this custom taxonomy (i.e. /taxonomy-name/taxonomy-term/) I get the following error:

`Fatal error: Access to undeclared static property: WP_DFP_Frontend::$taxonomy in /srv/www/wordpress-default/wp-content/plugins/wp-dfp/wp-dfp-frontend.php on line 150`

I have no such problem on either the category or tag archive pages.

I'm far from 100% but looking at the relevant line in wp-dfp-frontend.php, I wonder if it should be:

`$taxonomy = get_queried_object()->slug` rather than `self::$taxonomy = get_queried_object()->slug`?

**Comment by jcowher** [comment]
Thanks @johnpuddephatt, definitely a typo there. Should be `$taxonomy = get_queried_object()->slug` like you said. I've got this fixed up in [1.1.6](https://github.com/oomphinc/wp-dfp/tree/1.1.6)

**Comment by cdharrison** [comment]
I know this issue is closed - and I do apologize for hopping in like this - but it appears that this issue is still happening in 1.1.7. In particular, I'm getting the same error on an archive page that's created by the [Organize Series](https://wordpress.org/plugins/organize-series/) plugin and WP-DFP.

> Access to undeclared static property: WP_DFP_Frontend::$taxonomy in <b>/home/qhn/public_html/wp-content/plugins/wp-dfp/wp-dfp-frontend.php</b> on line <b>150</b>
